version: '3.8'

services:
  # API Service (Your Express App)
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
    volumes:
      - .:/app
      # Mount a volume to prevent node_modules from being overwritten by the host directory
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    # This command automatically runs migrations and then starts the development server.
    command: sh -c "npm run db:push && npm run dev"

  # PostgreSQL Database Service
  db:
    image: postgres:16-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${DB_USERNAME} -d $${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

# Define the network
networks:
  app-network:
    driver: bridge

# Define the volume for data persistence
volumes:
  postgres-data:
